"""
urgency_scoring.py — Transparent Multi-Factor Urgency Classification
────────────────────────────────────────────────────────────────────────────
REPLACES metafusion_predict.py.

WHY THIS EXISTS:
  The previous metafusion_model.pkl was a GradientBoostingClassifier trained
  to reach 99.91% CV accuracy predicting "urgency_class" — but the training
  labels were themselves generated by simple threshold rules stored in
  urgency_labelling_rules.json (e.g. severity_day7 >= 70 -> Emergency).
  A model trained to predict the output of a rule, using the same inputs
  the rule reads, will trivially memorise that rule. The 99.91% accuracy
  reflected how well it memorised the rule, not learned intelligence.
  That made the "zero hardcoded thresholds — all decisions from a trained
  classifier" claim misleading: the thresholds didn't disappear, they were
  just relocated and given an ML-shaped wrapper.

WHAT THIS MODULE DOES INSTEAD:
  An explicit, disclosed, multi-factor WEIGHTED SCORING function. Every
  contributing factor and its weight is visible in urgency_weights.json
  (auto-generated with documented defaults below). Nothing is hidden inside
  a black-box model pretending to have learned something it memorised.

  This is honest about what it is: a transparent decision-support formula,
  not a trained classifier. It is still a genuine, multi-factor synthesis
  of 12+ upstream model outputs (image severity, soil class, composite
  risk, geo risk, outbreak class, spread velocity, geo momentum, treatment
  history) — which is itself a defensible technical contribution distinct
  from a single severity-threshold check.

PATH TO BECOMING GENUINELY LEARNED:
  Once /feedback accumulates enough REAL post-treatment outcomes (not
  rule-generated labels), retrain_service.py can fit a model against those
  real outcomes (e.g. "given this state, did severity actually improve
  within N days") instead of against rule-derived labels. That would be
  genuine learned intelligence. Until then, this transparent formula is
  the more honest choice — and the weights here can be hand-tuned or
  adjusted by retrain_service.py based on real feedback without needing
  a fragile retrained black box.

SAME INTERFACE AS metafusion_predict.predict_urgency() — drop-in
replacement. No caller needs to change.
"""

import os
import json
import logging

logger = logging.getLogger(__name__)
BASE = os.path.dirname(os.path.abspath(__file__))
WEIGHTS_PATH = os.path.join(BASE, "urgency_weights.json")

CLASSES = ["Preventive", "Standard", "Urgent", "Emergency"]

# ──────────────────────────────────────────────────────────────────────────
# DEFAULT WEIGHTS — documented reasoning per factor
# ──────────────────────────────────────────────────────────────────────────
DEFAULT_WEIGHTS = {
    # Current observed severity from the leaf image model — direct evidence
    "severity":                 0.25,
    # 7-day predicted severity — forward-looking signal, arguably more
    # decision-relevant than the current snapshot
    "severity_day7":            0.20,
    # Existing composite risk classification (temp/humidity/soil/severity fusion)
    "composite_risk_enc":       0.13,
    # Geo-spatial outbreak risk for this region
    "geo_risk_enc":              0.12,
    # Regional outbreak classification (neighbouring farms reporting same disease)
    "outbreak_class_enc":       0.10,
    # How fast the disease is spreading spatially right now
    "spread_velocity":          0.10,
    # Trend of geo risk over the recent sliding window (rising vs falling)
    "geo_momentum":             0.05,
    # If past treatments for this field/disease have been ineffective,
    # that itself raises urgency (escalation signal) — inverse contribution
    "treatment_ineffectiveness": 0.05,
}

# Band boundaries on the 0-100 composite score. Disclosed, not hidden.
DEFAULT_BANDS = {
    "Preventive": [0, 20],
    "Standard":   [20, 45],
    "Urgent":     [45, 70],
    "Emergency":  [70, 100],
}


def _load_weights() -> dict:
    if os.path.exists(WEIGHTS_PATH):
        try:
            with open(WEIGHTS_PATH) as f:
                data = json.load(f)
            if "weights" in data and "bands" in data:
                return data
        except Exception as e:
            logger.warning(f"urgency_weights.json unreadable, using defaults: {e}")

    data = {"weights": DEFAULT_WEIGHTS, "bands": DEFAULT_BANDS, "schema_version": 1}
    try:
        with open(WEIGHTS_PATH, "w") as f:
            json.dump(data, f, indent=2)
    except Exception:
        pass
    return data


def _normalise(value: float, lo: float, hi: float) -> float:
    """Clamp + scale any input to a 0-100 contribution scale."""
    if hi <= lo:
        return 0.0
    v = max(lo, min(hi, value))
    return (v - lo) / (hi - lo) * 100.0


def _band_for_score(score: float, bands: dict) -> str:
    for cls in CLASSES:
        lo, hi = bands.get(cls, DEFAULT_BANDS[cls])
        if lo <= score < hi or (cls == "Emergency" and score >= lo):
            return cls
    return "Standard"


def predict_urgency(
    severity: float,
    disease_confidence: float,
    disease_class_id: int,
    soil_class_enc: int,
    soil_prob_poor: float,
    composite_risk_enc: int,
    composite_risk_prob_high: float,
    severity_day7: float,
    geo_risk_enc: int,
    geo_risk_prob_high: float,
    outbreak_class_enc: int,
    outbreak_prob_outbreak: float,
    spread_velocity: float,
    geo_momentum: float,
    treatment_effectiveness: float,
) -> dict:
    """
    Same signature and same return shape as the old metafusion_predict.py,
    so no caller (pipeline.py, rl_engine.py, feedback_predict.py) needs to
    change. Internals are now a transparent weighted formula instead of a
    black-box model trained on its own rules.

    Returns:
      urgency_class, urgency_class_enc, confidence, all_probs, top_factors
    """
    cfg     = _load_weights()
    weights = cfg["weights"]
    bands   = cfg["bands"]

    # ── Normalise every factor to a comparable 0-100 contribution scale ──
    contributions = {
        "severity":                  weights["severity"]                  * _normalise(severity, 0, 100),
        "severity_day7":             weights["severity_day7"]             * _normalise(severity_day7, 0, 100),
        "composite_risk_enc":        weights["composite_risk_enc"]        * _normalise(composite_risk_enc, 0, 2),
        "geo_risk_enc":               weights["geo_risk_enc"]              * _normalise(geo_risk_enc, 0, 2),
        "outbreak_class_enc":        weights["outbreak_class_enc"]        * _normalise(outbreak_class_enc, 0, 2),
        "spread_velocity":           weights["spread_velocity"]           * _normalise(spread_velocity, 0, 1),
        "geo_momentum":              weights["geo_momentum"]              * _normalise(abs(geo_momentum), 0, 1),
        "treatment_ineffectiveness": weights["treatment_ineffectiveness"] * _normalise(1 - treatment_effectiveness, 0, 1),
    }

    composite_score = round(sum(contributions.values()), 4)
    composite_score = max(0.0, min(100.0, composite_score))

    urgency_class     = _band_for_score(composite_score, bands)
    urgency_class_enc = CLASSES.index(urgency_class)

    # ── Honest confidence: distance from the nearest band boundary ──────
    lo, hi = bands[urgency_class]
    band_width = max(hi - lo, 1)
    dist_from_edge = min(composite_score - lo, hi - composite_score)
    confidence = round(0.5 + 0.5 * min(1.0, dist_from_edge / (band_width / 2)), 4)

    # ── all_probs: soft membership based on distance to each band centre ─
    all_probs = {}
    for cls in CLASSES:
        c_lo, c_hi = bands[cls]
        centre = (c_lo + c_hi) / 2
        dist = abs(composite_score - centre)
        all_probs[cls] = dist
    max_dist = max(all_probs.values()) or 1
    all_probs = {cls: round(1 - (d / max_dist) * 0.9, 4) for cls, d in all_probs.items()}
    # Normalise to sum to 1 for interface compatibility
    total = sum(all_probs.values()) or 1
    all_probs = {cls: round(v / total, 4) for cls, v in all_probs.items()}

    # ── top_factors: real contribution-based attribution, not a proxy ───
    top_factors = sorted(
        [{"feature": k, "importance": round(v / max(composite_score, 0.01), 4), "value": round(v, 2)}
         for k, v in contributions.items()],
        key=lambda x: -x["value"]
    )[:5]

    return {
        "urgency_class":      urgency_class,
        "urgency_class_enc":  urgency_class_enc,
        "confidence":         confidence,
        "all_probs":          all_probs,
        "top_factors":        top_factors,
        "composite_score":    composite_score,
        "method":             "transparent_weighted_scoring",   # honest disclosure, always present
    }
